### ISSUE TITLE
Could not connect to local LLM

### ISSUE THREAD

**Issue by JohnZolton** [dzhng/deep-research#52]
I solved this by adding this to docker-compose.yml:

```
services:
  deep-research:
    build: .
    env_file:
      - .env.local
    tty: true
    stdin_open: true
    network_mode: "host" # add this line
```
